# class TplEnums():
# FormFilter 内容标识
REPLACE_FORM_CONTENT = '##REPLACE_FORM_CONTENT##'
# FormFilter 单项名称
REPLACE_TITLE = '##REPLACE_TITLE##'
# FormFilter 对应的KeyName
REPLACE_KEY_NAME = '##REPLACE_KEY_NAME##'
# FormFilter 单项 Placeholder
REPLACE_HINT = '##REPLACE_HINT##'
# FormFilter 选择类型项目的 Val替换
REPLACE_OPTION_VAL = '##REPLACE_OPTION_VAL##'
# FormFilter 选择类型项目的 name 替换
REPLACE_OPTION_TITLE = '##REPLACE_OPTION_TITLE##'
# FormFilter 选择类型的 Options 部分替换
REPLACE_OPTIONS = '##REPLACE_OPTIONS##'
# Content 每一列的标题部分
REPLACE_ITEM_TITLE = '##REPLACE_ITEM_TITLE##'
# Content 每一列对应的key
REPLACE_ITEM_KEY = '##REPLACE_ITEM_KEY##'
# Content 替换部分
REPLACE_CONTENT_ITEMS = '##REPLACE_CONTENT_ITEMS##'
# Content width 百分比替换部分
REPLACE_ITEM_WIDTH = '##REPLACE_ITEM_WIDTH##'
# Manage 筛选条件部分替换
REPLACE_MANAGE_FILTER = '##REPLACE_MANAGE_FILTER##'
# Manage api导出名称
REPLACE_MANAGE_API = '##REPLACE_MANAGE_API##'
# Manage api 方法名称
REPLACE_MANAGE_API_METHOD = '##REPLACE_MANAGE_API_METHOD##'
# 分页参数 - 页 no
REPLACE_MANAGE_PAGE_NO = '##REPLACE_MANAGE_PAGE_NO##'
# 分页参数 - 页 size
REPLACE_MANAGE_PAGE_SIZE = '##REPLACE_MANAGE_PAGE_SIZE##'
